version: "3.9"
services:
  app: # name of the first service
    image: jitske0/gamediatefrontend:latest
    ports:
      - "4200:4200" # specify port forewarding
  backend: # name of the third service
    image: jitske0/gamediatebackend:latest # specify image to build container from
    ports:
      - "44300:80" #specify ports forewarding
