version: "3.9"
services:
  angular: # name of the first service
    build: C:\Users\Jitske\OneDrive\Documents\GitHub\Gamediate-Front-end\Dockerfile # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
  backend: # name of the third service
    image: jitske0/gamediatebackend:latest # specify image to build container from
    ports:
      - "44300:44300" #specify ports forewarding
