
# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:latest as build
LABEL author="Jitske"

# Set the working directory
WORKDIR /usr/local/app

# Add the source code to app
COPY ./ /usr/local/app/

# Install all the dependencies
RUN npm install -g npm@8.1.2

# Generate the build of the application
RUN npm run build

# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist/gamediate-front-end /usr/share/nginx/html

# Expose port 80
EXPOSE 80 3000

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
